### PR TITLE
Feat: Configuration for dependency injection

### PR DESCRIPTION
**Pull request by jskeet**

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
Travis is failing though.

**Comment by jskeet** [comment]
Whoops, will check. Suspect it's a silly mistake. Additionally, I want to get feedback from the original feature requester before merging.

**Comment by jskeet** [comment]
Fixed the error - not sure why I didn't pick up on it before. It's nice to have CI :)

**Comment by jskeet** [comment]
Abandoning in favour of #117.

**Pull request closed without merging**
