### PR TITLE
Add (and use) ConfigureFunctionsFramework extension method

### LINKED ISSUE #181: Accessing UseServiceProviderFactory method
Hi,

Is it possible to call UseServiceProviderFactory somehow? In ordinary projects, We are doing it in Main function in Program.cs. But now it looks we don't have access to Program.cs.

### PR DESCRIPTION
**Pull request by jskeet**
This allows for user customization of the host builder before we get to it (via a custom entry point)

Fixes #181

### CODE REVIEW

**Comment by jskeet** [comment]
(Example needed, when I've confirmed that this is what we want.)

**Comment by gkinsman** [comment]
Hi there! In case you're after another example simpler than Autofac integration, may I suggest using Serilog as the root logger instead of MSEL? 

The integration point is [here](https://github.com/serilog/serilog-aspnetcore/blob/dev/src/Serilog.AspNetCore/SerilogWebHostBuilderExtensions.cs), and adds a few things to services too.

This would fit your PR scenario well I think, as with Serilog its a good idea to wrap the entry point in a try/finally to catch startup errors, and to configure the logger before the app starts.

**Comment by jskeet** [comment]
@gkinsman: I'd happily revisit this PR if it becomes necessary, but this was specifically requested for Autofac integration.

Can Serilog integration not be done just with ConfigureLogging? If not, and if you're an interested customer requesting Serilog integration, I can look at it - but I'd rather not spend the time going back to this unless it's really required.

**Comment by jskeet** [comment]
Closing as I don't think we'll want to do this any time soon, although I'll leave the branch available.

**Pull request closed without merging**
