### PR TITLE
ci: add dotnet format tool for linting

### PR DESCRIPTION
**Pull request by grant**
- Adds dotnet format tool CI workflow
- Runs format tool

Hoping to add another green box on https://github.com/GoogleCloudPlatform/functions-framework

### CODE REVIEW

**Comment by jskeet** [comment]
I'd *at least* want to change the settings to have a space around casts. It's not *accidental* that they're there - I find them more readable that way.

I'm fine losing the whitespace lines - but this does feel like work that isn't actually adding any customer value.

**Comment by grant** [comment]
I'm indifferent about the specific formatting rules and was just using the defaults.

Is there a config we want to use with `dotnet-format` other than the default?

**Comment by jskeet** [comment]
> Is there a config we want to use with dotnet-format other than the default?

I don't know, because I've never looked into it - it's simply never been something we've pursued.

**Comment by grant** [comment]
I updated the editor config to have a space after cast. Other configs would be default.

Here's an example config:
https://github.com/dotnet/format/blob/master/tests/projects/for_code_formatter/formatted_project/.editorconfig

**Review by jskeet — APPROVED** [review]
Given that you've done all the work for this, I'm happy enough for this to go in, which isn't to say it's something I'd want to do elsewhere.

**Comment by grant** [comment]
Oh I spent <20 minutes on this. Was just talking with Vinod in making sure the test grid is all green.

If it at all not idiomatic or gets in the way after a bit, please revert.

**Pull request merged**
