### PR TITLE
Fix xml comment compiler warning

### PR DESCRIPTION
**Pull request by alteredego**

### CODE REVIEW

**Comment by jskeet** [comment]
Will just have a look before we merge this as to why I didn't spot it before...

**Comment by jskeet** [comment]
Hmm... I can't see a warning here at all, and in VS I can use F12 to get to `LogImpl<TState>`. I don't object to the change, but could you let me know what's warning you? Is this a Resharper warning, for example?

**Comment by alteredego** [comment]
You're absolutely right, it must be R# giving the warning - "Cannot resolve reference in XML comment".  It's the only error it shows in the solution and underlines the reference, but F12 does jump to the correct place in Visual Studio without the change.  I think the suggested change is "correct" though.

**Comment by jskeet** [comment]
Righto - that's fine then; will merge. I just wanted to check that I didn't need to change any warning flags etc first.

**Review by jskeet — APPROVED** [review]

**Pull request merged**
