### PR TITLE
Update Functions Framework Conformance submodule

### PR DESCRIPTION
**Pull request by mtraver**
This corresponds to version v0.3.10 of the conformance tests.

### CODE REVIEW

**Review by jskeet — APPROVED** [review]
Not sure why this is a draft PR, but if the tests pass I'm happy for it to be merged :) (Well, rebase-and-merge.)

**Comment by mtraver** [comment]
> Not sure why this is a draft PR, but if the tests pass I'm happy for it to be merged :) (Well, rebase-and-merge.)

The tests don't pass, so I made it a draft PR. I made a change in the conformance test client that more cleanly kills the FF serving process(es) but it doesn't work for Windows so I need to make another change in the conformance client first.

**Comment by mtraver** [comment]
Now tests pass!

**Comment by jskeet** [comment]
Fab. Will take a look when I get a chance.

**Pull request merged**
